/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'j1659' at '2017/2/25 下午 11:04' with Gradle 2.14.1
 *
 * @author j1659, @date 2017/2/25 下午 11:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
